// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/gofiber/fiber/v2"
	"go-music-scrapper/router"
)

// Injectors from injector.go:

func InjectUserService(app *fiber.App) *router.V1 {
	api := router.BuildApiEndpoint(app)
	v1 := router.BuildV1Endpoint(api)
	return v1
}
